-keep class io.github.supermonster003.autojs6.plugin.fileinspector.ExplorerActionService { *; }
-keep class io.github.supermonster003.autojs6.plugin.fileinspector.FileInspectorActivity { *; }
-keep class io.github.supermonster003.autojs6.plugin.fileinspector.WakeActivity { *; }
-keep class org.autojs.plugin.common.api.PluginInfo { *; }
-keep class org.autojs.plugin.explorer.api.** { *; }
